<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net48</TargetFramework>
    <RootNamespace>osu_TipToggle</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<LangVersion>latest</LangVersion>
	<AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
	<ApplicationIcon>Assets\pen.ico</ApplicationIcon>
	<Version>0.0.3</Version>
	<AssemblyVersion>0.0.3</AssemblyVersion>
	<FileVersion>0.0.3</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\pen.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OsuMemoryDataProvider" Version="0.11.1" />
  </ItemGroup>

</Project>
